[package]
name = "pi_orca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
pi_spatialtree = "0.3"
nalgebra = "0.30"
pi_slotmap="0.1"
ncollide2d = "0.33"
pi_path_finding = "0.3.0"
# rand = "0.8"